---
# tasks file for 2do_parcial

# Crear estructura de directorios
- name: Crear estructura de directorios
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'  # Permisos opcionales
  loop:
    - "/home/lucas/repogit/UTN-FRA_SO_Examenes/202406/ansible/tmp/2do_parcial"
    - "/home/lucas/repogit/UTN-FRA_SO_Examenes/202406/ansible/tmp/2do_parcial/alumno"
    - "/home/lucas/repogit/UTN-FRA_SO_Examenes/202406/ansible/tmp/2do_parcial/equipo"

# Crear archivo de datos del alumno usando template
- name: Crear archivo datos_alumno.txt usando template
  ansible.builtin.template:
    src: "templates/datos_alumno.txt.j2"
    dest: "/home/lucas/repogit/UTN-FRA_SO_Examenes/202406/ansible/tmp/2do_parcial/alumno/datos_alumno.txt"
    mode: '0644'  # Permite la lectura del archivo una vez creado


# Crear archivo de datos del equipo usando template
- name: Generar datos_equipo.txt con template
  ansible.builtin.template:
    src: "templates/datos_equipo.txt.j2"
    dest: "/home/lucas/repogit/UTN-FRA_SO_Examenes/202406/ansible/tmp/2do_parcial/equipo/datos_equipo.txt"
    mode: '0644'  # Permite la lectura del archivo una vez creado


# Crear el grupo 2PSupervisores si no existe
- name: Crear el grupo 2PSupervisores si no existe
  become: true
  group:
    name: 2PSupervisores
    state: present


# Configurar sudoers para grupo 2PSupervisores
- name: Configurar sudoers para grupo 2PSupervisores
  become: true
  lineinfile:
    path: /etc/sudoers
    line: "%2PSupervisores ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: '/usr/sbin/visudo -cf %s'
